# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files

-   repo: local
    hooks:
    -   id: lint
        name: Lint
        entry: nox
        args: ['-s', 'lint']
        language: system
        types: [python]
        pass_filenames: false
        always_run: true

    -   id: test
        name: Test
        entry: nox
        args: ['-s', 'unit_tests']
        language: system
        types: [python]
        pass_filenames: false

    -   id: docs
        name: Docs
        entry: nox
        args: ['-s', 'build_docs']
        language: system
        types: [file, python]
        pass_filenames: false
