# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files

-   repo: local
    hooks:
    -   id: yapf
        name: Format with YAPF
        entry: poetry run yapf
        language: system
        types: [python]
        args: [--in-place, --recursive, --parallel]

    -   id: isort
        name: isort
        entry: poetry run isort
        language: system
        types: [python]

    -   id: flake8
        name: Check with Flake8
        entry: poetry run flake8
        language: system
        pass_filenames: true
        types: [python]
        args: [--count]

    -   id: mypy
        name: Validate types with MyPy
        entry: poetry run mypy
        language: system
        types: [python]
